name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '10 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue is stale because it has been open 28 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 28 days with no activity.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          days-before-stale: 28
          days-before-close: 7
          close-issue-reason: 'not_planned'
          
